### ISSUE TITLE
Research semantic commit messages

### ISSUE THREAD

**Issue by atareversei** [basliqacademy/hnahz#2]
Research semantic commit messages and comment your findings below this issue.

**Comment by hnahz** [comment]
Semantic commit messages is a kind of standard for writing commits and its purpose is to write readable commits. Its general structure is as follows:

```<type>(<scope>): <description>```
- type: Specifies the type of change made.
- scope (optional): Refers to the part where the changes are implemented.
- description: A summary of the purpose of the commit.


Here are the most common types of commit messages used in semantic commits:

- feat: A new feature is added to the codebase.
- fix: A bug or issue is fixed.
- docs: Documentation changes (like README updates).
- style: Code style or formatting changes that don’t affect functionality.
- refactor: Code changes that neither fix a bug nor add a feature but improve the code structure.
- test: Adding or updating tests.
- chore: Routine tasks such as updating dependencies or build scripts that do not affect the source code.
- perf: Changes that improve performance.
- ci: Continuous integration changes.
